package com.example.restassuredproject.utility

class ApiPath {
    //staging

    public static final String hostURL2="http://10.9.0.41:8080/nobopay-api-gateway/api/v1/user/signup/attempt"
    public static final String hostURL3="http://10.9.0.41:8080/npSpring_qa-"
    public static final String otpValidationPath="http://10.9.0.41:8080/nobopay-api-gateway/api/v1/user/otp/verify"
    public static final String createWallet="http://10.9.0.41:8080/nobopay-api-gateway/api/v1/user/signup/wallet"
    public static final String nidFrontUpload="http://10.9.0.41:8080/nobopay-api-gateway/api/v1/user/doc/nid-front"
    public static final String hostURLForNIDClear="http://10.9.0.41:9113"
    public static final String otpValidation="/api/v1/otp/verify"
    //staging
    public static final String createWalletPath="/api/v1/user/signup/wallet"
    public static final String setLoginPath="/api/v1/user/login"
    public static final String docUploadPath="/api/v1/user/doc/NID_FRONT"
    public static final String docUploadPath2="/api/v1/user/doc/NID_BACK"
    public static final String userInfoUpdatePath="/api/v1/user"
    public static final String portalLoginPath="/api/portal/login"
    public static final String getUserDocDetailsPath="/nobopay-backend/api/profile/extended/"
    public static final String docStatusUpdatePath="/nobopay-backend/api/document/verify"
    public static final String userStatusChangePath="/api/portal/wallet/status"
    public static final String addBankAccPath="/api/v1/account/bank"
    public static final String bankAccGetPath="/api/v1/account"
    public static final String amtVerificationPath="/api/micro-txn"
    public static final String verifyAccPath="/api/v1/account/bank/verify"
    public static final String addMoneyPath="/api/v1/transaction/load-money/bank"
    public static final String createIDTPAccPath="/api/v1/account/idtp"
    public static final String fundTransferPath="/api/v1/transaction/idtp/send-money"
    public static final String idtpPaymentPath="/api/v1/transaction/idtp/payment"
    public static final String rtpReqPath="/api/v1/transaction/idtp/request-rtp"
    public static final String rtpRequestListPath="/api/v1/transaction/idtp/rtp"
    public static final String processRTPRequestList="/api/v1/transaction/idtp/response-to-rtp"
    public static final String validateIDTPVIDPath="/api/v1/account/idtp/"
    public static final String validateIDTPVIDPath2="/validate-vid"
    public static final String getBalanceApiPath="/nobopay-api-gateway/api/v1/wallet/balance"
    public static final String ekycNidFrontPath="/api/v1/user/doc/nid-front"
    public static final String ekycNidBackPath="/api/v1/user/doc/nid-back"
    public static final String ekycProfilePicturePath="/api/v1/user/doc/face-image"
    public static final String nidConfirmationPath="/api/v1/user/doc/confirm-nid-info"
    public static final String nidClearAPIPath="/api/backend/nid/"
    public static final String nidClearAPIPath2="/reset-nid"



    public static final String regPAthS="/nobopay-api-gateway/api/v1/user/signup/attempt"
    public static final String getOTPPathS="/npSpring_qa-/get/otp/"
    public static final String validateOTPPathS="/nobopay-api-gateway/api/v1/user/otp/verify"
    public static final String createWalletPathS="/nobopay-api-gateway/api/v1/user/signup/wallet"
    public static final String deviceRegPathS="/nobopay-api-gateway/api/v1/device/register"
    public static final String ekycNidFrontPathS="/nobopay-api-gateway/api/v1/user/doc/nid-front"
    public static final String ekycNidBackPathS="/nobopay-api-gateway/api/v1/user/doc/nid-back"
    public static final String nidConfirmationPathS="/nobopay-api-gateway/api/v1/user/doc/confirm-nid-info"
    public static final String nomineeInfoS="/nobopay-api-gateway/api/v1/user/nominee"
    public static final String ekycProfilePicturePathS="/nobopay-api-gateway/api/v1/user/doc/face-image"
    public static final String setLoginPathS="/nobopay-api-gateway/api/v1/user/login"
    public static final String addBankAccPathS="/nobopay-api-gateway/api/v1/account/bank"
    public static final String  bankAccGetPathS="/nobopay-api-gateway/api/v1/account"
    public static final String verifyAccPathS="/nobopay-api-gateway/api/v1/account/bank/verify"
    public static final String addMoneyPathS="/nobopay-api-gateway/api/v1/transaction/load-money/bank"
    public static final String createIDTPAccPathS="/nobopay-api-gateway/api/v1/account/idtp"
    public static final String fundTransferPathS="/nobopay-api-gateway/api/v1/transaction/idtp/send-money"
    public static final String idtpPaymentPathS="/nobopay-api-gateway/api/v1/transaction/idtp/payment"
    public static final String rtpReqPathS="/nobopay-api-gateway/api/v1/transaction/idtp/request-rtp"
    public static final String rtpRequestListPathS="/nobopay-api-gateway/api/v1/transaction/idtp"
    public static final String processRTPRequestListS="/nobopay-api-gateway/api/v1/transaction/idtp/response-to-rtp"
    public static final String sendMoneyPathS="/nobopay-api-gateway/api/v1/transaction/send-money"
    public static final String paymentPathS="/nobopay-api-gateway/api/v1/transaction/merchant-payment"
    public static final String mobileRechargePathS="/nobopay-api-gateway/api/v1/transaction/recharge-mobile"
    public static final String bankCashOutPathS="/nobopay-api-gateway/api/v1/transaction/cash-out/bank"
    public static final String walletStmtRequestListPathS="/nobopay-api-gateway/api/v1/wallet/statement"
    public static final String changePINPathS="/nobopay-api-gateway/api/v1/user/pin"
    public static final String resetPINPathS="/nobopay-api-gateway/api/v1/user/pin/reset"
    public static final String resetPINFromPortalPathS="/api/portal/user/pin/reset"

}